# Do not edit. Generated by the configure script.
export PATH:=/Users/harimohanraj/Documents/Mathura/PaperCraneLab/env-12.10.0/src/node-v12.10.0/out/tools/bin:$(PATH)
PYTHON=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
BUILDTYPE=Release
PREFIX=/Users/harimohanraj/Documents/Mathura/PaperCraneLab/env-12.10.0
NODE_TARGET_TYPE=executable
